// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(user_id, name, type, currency, balance)
VALUES($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, currency, balance, created_at, updated_at
`

type CreateAccountParams struct {
	UserID   uuid.UUID
	Name     string
	Type     string
	Currency string
	Balance  int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts
WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountForUser = `-- name: GetAccountForUser :one
SELECT id, user_id, name, type, currency, balance, created_at, updated_at FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccountForUser(ctx context.Context, arg GetAccountForUserParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUser, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, type, currency, balance, created_at, updated_at FROM accounts
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1, type = $2, updated_at = now()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, name, type, currency, balance, created_at, updated_at
`

type UpdateAccountParams struct {
	Name   string
	Type   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.ID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
